eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8010/eureka
    prefer-ip-address: true
  instance:
    prefer-ip-address: true
server:
  port: 8888
spring:
  application:
    name: apigateway-ws
  devtools:
    restart:
      enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true